export { VM } from "./vm.ts";
export type { Frame, Signal, VMOptions, Handler } from "./vm.ts";
export { Scope } from "./scope.ts";
export type { Binding, BindingKind } from "./scope.ts";
export { parse, syntaxKindName, ts } from "./frontend.ts";
export { createVM, createTypedVM, interpret } from "./interpret.ts";
export type { InterpretOptions } from "./interpret.ts";
export { createTypedProgram, typeOfNode } from "./program.ts";
export type { TypedProgram } from "./program.ts";
export { isGuestFunction } from "./values.ts";
export type { GuestFunction, GuestFunctionMeta } from "./values.ts";
export { nodeHandlers, syntheticHandlers, createGuestFunction } from "./handlers.ts";
export { TsvalInternalError, unimplemented, isUncatchable, UNCATCHABLE } from "./errors.ts";
export { runCanary, safeGlobals, covers, CanaryDivergenceError } from "./canary.ts";
export type { CanaryEvent, CanaryReport, CanaryOptions } from "./canary.ts";
